language: cpp
compiler: gcc

before_install:
  - gem install coveralls-lcov

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - cd ..

after_success:
  - coveralls-lcov --repo-token mo2RCaOKRqRqBT8utItWC973wjmy8gUy4 build/coverage.info

