language: cpp
compiler: gcc

before_install:
  - gem install coveralls-lcov

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - cd ..

after_success:
  - coveralls-lcov --repo-token 7nP4T5wrd5kiKQJZy5isFaTvUGoUUcNjO build/coverage.info

